adopt configure for macOS

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3,15 +3,46 @@ if test -z "${R_HOME}"; then
   echo "could not determine R_HOME"
   exit 1
 fi
+
 CC=`"${R_HOME}/bin/R" CMD config CC`
 CFLAGS=`"${R_HOME}/bin/R" CMD config CFLAGS`
 CPPFLAGS=`"${R_HOME}/bin/R" CMD config CPPFLAGS`
 LDFLAGS=`"${R_HOME}/bin/R" CMD config LDFLAGS`
 
+if test -z "$CMAKE"; then CMAKE="`which cmake`"; fi
+if test -z "$CMAKE"; then CMAKE=/Applications/CMake.app/Contents/bin/cmake; fi
+if test -f "$CMAKE"; then echo "found cmake!"; else echo "no ‘cmake’ command found"; exit 1; fi
+
+## check for libtool
+# if test -n "`which libtool`"
+# then
+#   echo "Found libtool at `which libtool`"
+#   libtool --version
+if test -f "/Applications/CMake.app/Contents/bin/cmake"
+then
+  export PATH=${R_HOME}/bin/:$PATH
+  echo "using libtool from R installation"
+  echo "`which libtool`"
+  $LIBTOOL --version
+elif test -n "`which libtool`"
+then
+   echo "Found libtool at `which libtool`"
+   libtool --version
+else
+  echo "libtool not found"
+  exit 1
+fi
+
 tar -xf tools/arpack-ng-3.9.0.tar.gz -C src
 cd src/arpack-ng-3.9.0
 sh bootstrap
 ./configure --enable-icb
-mkdir -p build
-cd build && cmake -D ICB=ON -D BUILD_SHARED_LIBS=NO -D TESTS=OFF -D EXAMPLES=OFF -D CMAKE_C_FLAGS=-fPIC -D CMAKE_Fortran_FLAGS=-fPIC ..
+mkdir -p build && cd build
+${CMAKE} -D ICB=ON -D BUILD_SHARED_LIBS=NO -D TESTS=OFF -D EXAMPLES=OFF -D CMAKE_C_FLAGS=-fPIC -D CMAKE_Fortran_FLAGS=-fPIC ..
 ${MAKE}
+echo "Files in build:"
+ls -l
+echo "Files in ."
+ls -l ../
+echo "Files in ICB"
+ls -l ../ICB
